services:
  - type: web
    name: ordskin
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      flask db upgrade &&
      gunicorn run:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false


