services:
  - type: web
    name: ordskin
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python init_db.py &&
      flask db upgrade &&
      gunicorn run:app