services:
  - type: web
    name: ordskin
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      flask db upgrade &&
      gunicorn run:app  # update `app:app` if needed (format: filename:FlaskAppInstance)
