services:
  - type: web
    name: ordskin
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      flask db upgrade &&
      gunicorn run:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ordskin
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false  # DO NOT hardcode it here
