"""Modified brand_id to nullable-false

Revision ID: 66936dcf94d5
Revises: b41fa23bb529
Create Date: 2025-07-29 21:52:25.198274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66936dcf94d5'
down_revision = 'b41fa23bb529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
