"""added hidden feature to product

Revision ID: 81caf279aff8
Revises: 66936dcf94d5
Create Date: 2025-07-29 23:41:51.048468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81caf279aff8'
down_revision = '66936dcf94d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###
