"""added purchased x times feature

Revision ID: 8dfdae6c0fb1
Revises: 94c3eb42588e
Create Date: 2025-07-29 03:32:22.675807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfdae6c0fb1'
down_revision = '94c3eb42588e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased_times', sa.Integer(), nullable=True))
        batch_op.drop_column('purchasedTimes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchasedTimes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('purchased_times')

    # ### end Alembic commands ###
