"""added purchased x times feature

Revision ID: 8e8cf978208f
Revises: 8dfdae6c0fb1
Create Date: 2025-07-29 03:34:00.755340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8cf978208f'
down_revision = '8dfdae6c0fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_column('purchased_times')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased_times', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('products_brand_id_fkey'), type_='foreignkey')
        batch_op.drop_column('brand_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('products_brand_id_fkey'), 'brands', ['brand_id'], ['id'])
        batch_op.drop_column('purchased_times')

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased_times', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
