"""added purchased x times feature

Revision ID: 94c3eb42588e
Revises: de0dcc1542a7
Create Date: 2025-07-29 03:30:35.516921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c3eb42588e'
down_revision = 'de0dcc1542a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchasedTimes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_column('purchasedTimes')

    # ### end Alembic commands ###
