"""removed hidden column from products

Revision ID: dc094d86b99c
Revises: 98055cfa5d4f
Create Date: 2025-08-02 01:04:02.798058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc094d86b99c'
down_revision = '98055cfa5d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
